### ISSUE TITLE
Nothing happens on project export

### ISSUE THREAD

**Issue by Jurek-Raben** [bitwig/dawproject#12] opened 2021-06-26 11:42 UTC
Hi,
with beta 5, nothing happens here on "project export", no file will be created. macos 10.14.6 here

**Comment by git-moss** [comment] 2021-06-26 15:49
Works for me (Windows 10).

**Comment by Jurek-Raben** [comment] 2021-07-03 10:01
Hm still nothing happens with Beta6 macos mojave, JFYI

**Comment by git-moss** [comment] 2021-12-22 19:40
Duplicate of #24

**Comment by kurasu** [comment] 2022-02-11 13:51
problem was that it would only export if the .dawproject file extension was present, and the macOS dialog doesn't add that the same way as the windows one.

**Closed by kurasu** 2022-02-11 13:51 UTC
